import { useState } from 'react'
import Table from '@/components/ui/Table'
import {
    flexRender,
    getCoreRowModel,
    getSortedRowModel,
    useReactTable,
    getFilteredRowModel,
    getPaginationRowModel

} from '@tanstack/react-table'
import type { ColumnDef, ColumnSort } from '@tanstack/react-table'

import Pagination from '@/components/ui/Pagination'
import Select from '@/components/ui/Select'

type Usuario = {
    id: number
    nombre: string
    activo: number
}

type Option = {
    value: number
    label: string
}

const columns: ColumnDef<Usuario>[] = [
    {
        header: 'Id',
        accessorKey: 'id',
    },
    {
        header: 'Nombre',
        accessorKey: 'nombre',
    },
    {
        header: 'Activo',
        accessorKey: 'activo',
    },
]

const pageSizeOption = [
    { value: 10, label: '10 / pag.' },
    { value: 20, label: '20 / pag.' },
    { value: 30, label: '30 / pag.' },
    { value: 40, label: '40 / pag.' },
    { value: 50, label: '50 / pag.' },
]

const data2 = [{ "id": 1, "nombre": "Charla", "activo": 1 },
{ "id": 2, "nombre": "Noella", "activo": 0 },
{ "id": 3, "nombre": "Derron", "activo": 0 },
{ "id": 4, "nombre": "Far", "activo": 1 },
{ "id": 5, "nombre": "Deana", "activo": 1 },
{ "id": 6, "nombre": "Maryjo", "activo": 1 },
{ "id": 7, "nombre": "Dianemarie", "activo": 0 },
{ "id": 8, "nombre": "Vilhelmina", "activo": 1 },
{ "id": 9, "nombre": "Leigh", "activo": 0 },
{ "id": 10, "nombre": "Raymond", "activo": 0 },
{ "id": 11, "nombre": "Townie", "activo": 1 },
{ "id": 12, "nombre": "Heinrick", "activo": 1 },
{ "id": 13, "nombre": "Olly", "activo": 1 },
{ "id": 14, "nombre": "Marcos", "activo": 1 },
{ "id": 15, "nombre": "Cullan", "activo": 1 },
{ "id": 16, "nombre": "Quintilla", "activo": 1 },
{ "id": 17, "nombre": "Caleb", "activo": 1 },
{ "id": 18, "nombre": "Leslie", "activo": 1 },
{ "id": 19, "nombre": "Sayers", "activo": 1 },
{ "id": 20, "nombre": "Tonia", "activo": 1 },
{ "id": 21, "nombre": "Nicolis", "activo": 0 },
{ "id": 22, "nombre": "Bentlee", "activo": 0 },
{ "id": 23, "nombre": "Corrie", "activo": 1 },
{ "id": 24, "nombre": "Dixie", "activo": 1 },
{ "id": 25, "nombre": "Vasili", "activo": 0 },
{ "id": 26, "nombre": "Carilyn", "activo": 0 },
{ "id": 27, "nombre": "Rafaellle", "activo": 0 },
{ "id": 28, "nombre": "Chaim", "activo": 0 },
{ "id": 29, "nombre": "Tatiania", "activo": 1 },
{ "id": 30, "nombre": "Tabitha", "activo": 1 },
{ "id": 31, "nombre": "Gardener", "activo": 0 },
{ "id": 32, "nombre": "Tessi", "activo": 1 },
{ "id": 33, "nombre": "Celestina", "activo": 1 },
{ "id": 34, "nombre": "Darren", "activo": 1 },
{ "id": 35, "nombre": "Anthony", "activo": 0 },
{ "id": 36, "nombre": "Gianni", "activo": 0 },
{ "id": 37, "nombre": "Dorie", "activo": 0 },
{ "id": 38, "nombre": "Kikelia", "activo": 0 },
{ "id": 39, "nombre": "Georgiana", "activo": 1 },
{ "id": 40, "nombre": "Charita", "activo": 0 },
{ "id": 41, "nombre": "Rudolf", "activo": 0 },
{ "id": 42, "nombre": "Faustina", "activo": 0 },
{ "id": 43, "nombre": "Clemmie", "activo": 0 },
{ "id": 44, "nombre": "Bamby", "activo": 0 },
{ "id": 45, "nombre": "Stanfield", "activo": 0 },
{ "id": 46, "nombre": "Aigneis", "activo": 1 },
{ "id": 47, "nombre": "Antonin", "activo": 0 },
{ "id": 48, "nombre": "Griffy", "activo": 1 },
{ "id": 49, "nombre": "Carina", "activo": 0 },
{ "id": 50, "nombre": "Odo", "activo": 1 },
{ "id": 51, "nombre": "Elmore", "activo": 1 },
{ "id": 52, "nombre": "Sidonia", "activo": 1 },
{ "id": 53, "nombre": "Norrie", "activo": 0 },
{ "id": 54, "nombre": "Dara", "activo": 1 },
{ "id": 55, "nombre": "Waverley", "activo": 1 },
{ "id": 56, "nombre": "Dani", "activo": 1 },
{ "id": 57, "nombre": "Sloan", "activo": 0 },
{ "id": 58, "nombre": "Dorian", "activo": 0 },
{ "id": 59, "nombre": "Maxy", "activo": 1 },
{ "id": 60, "nombre": "Sydney", "activo": 1 },
{ "id": 61, "nombre": "Cordie", "activo": 0 },
{ "id": 62, "nombre": "Merill", "activo": 1 },
{ "id": 63, "nombre": "Agathe", "activo": 1 },
{ "id": 64, "nombre": "Waldon", "activo": 1 },
{ "id": 65, "nombre": "Udale", "activo": 0 },
{ "id": 66, "nombre": "Karin", "activo": 1 },
{ "id": 67, "nombre": "Pansie", "activo": 0 },
{ "id": 68, "nombre": "Vidovik", "activo": 0 },
{ "id": 69, "nombre": "Nikoletta", "activo": 1 },
{ "id": 70, "nombre": "Helen", "activo": 1 },
{ "id": 71, "nombre": "Fairlie", "activo": 0 },
{ "id": 72, "nombre": "Waverley", "activo": 1 },
{ "id": 73, "nombre": "Almira", "activo": 1 },
{ "id": 74, "nombre": "Myles", "activo": 1 },
{ "id": 75, "nombre": "Edlin", "activo": 1 },
{ "id": 76, "nombre": "Dorelle", "activo": 1 },
{ "id": 77, "nombre": "Ulla", "activo": 0 },
{ "id": 78, "nombre": "Elinore", "activo": 0 },
{ "id": 79, "nombre": "Forbes", "activo": 0 },
{ "id": 80, "nombre": "Mellisent", "activo": 0 },
{ "id": 81, "nombre": "Wilden", "activo": 1 },
{ "id": 82, "nombre": "Daron", "activo": 0 },
{ "id": 83, "nombre": "Frederik", "activo": 1 },
{ "id": 84, "nombre": "Vinnie", "activo": 1 },
{ "id": 85, "nombre": "Merridie", "activo": 0 },
{ "id": 86, "nombre": "Malena", "activo": 0 },
{ "id": 87, "nombre": "Merill", "activo": 1 },
{ "id": 88, "nombre": "Hortense", "activo": 0 },
{ "id": 89, "nombre": "Bridget", "activo": 0 },
{ "id": 90, "nombre": "Marcelle", "activo": 1 },
{ "id": 91, "nombre": "Leora", "activo": 1 },
{ "id": 92, "nombre": "Angelo", "activo": 1 },
{ "id": 93, "nombre": "Merissa", "activo": 0 },
{ "id": 94, "nombre": "Codie", "activo": 0 },
{ "id": 95, "nombre": "Waring", "activo": 0 },
{ "id": 96, "nombre": "Zacherie", "activo": 0 },
{ "id": 97, "nombre": "Tandie", "activo": 0 },
{ "id": 98, "nombre": "Martha", "activo": 0 },
{ "id": 99, "nombre": "Izabel", "activo": 1 },
{ "id": 100, "nombre": "Farris", "activo": 0 },
{ "id": 101, "nombre": "Dania", "activo": 1 },
{ "id": 102, "nombre": "Any", "activo": 0 },
{ "id": 103, "nombre": "Thomasa", "activo": 0 },
{ "id": 104, "nombre": "Reinald", "activo": 0 },
{ "id": 105, "nombre": "Rufe", "activo": 0 },
{ "id": 106, "nombre": "Kristy", "activo": 0 },
{ "id": 107, "nombre": "Stavro", "activo": 0 },
{ "id": 108, "nombre": "Maxy", "activo": 1 },
{ "id": 109, "nombre": "Cirstoforo", "activo": 0 },
{ "id": 110, "nombre": "Erastus", "activo": 1 },
{ "id": 111, "nombre": "Trudy", "activo": 0 },
{ "id": 112, "nombre": "Kiele", "activo": 0 },
{ "id": 113, "nombre": "Lev", "activo": 0 },
{ "id": 114, "nombre": "Saundra", "activo": 1 },
{ "id": 115, "nombre": "Hamel", "activo": 1 },
{ "id": 116, "nombre": "Pernell", "activo": 1 },
{ "id": 117, "nombre": "Lewes", "activo": 1 },
{ "id": 118, "nombre": "Mile", "activo": 1 },
{ "id": 119, "nombre": "Amitie", "activo": 0 },
{ "id": 120, "nombre": "Agosto", "activo": 1 },
{ "id": 121, "nombre": "Francesco", "activo": 1 },
{ "id": 122, "nombre": "Sadye", "activo": 1 },
{ "id": 123, "nombre": "Genevra", "activo": 1 },
{ "id": 124, "nombre": "Josias", "activo": 1 },
{ "id": 125, "nombre": "Lesly", "activo": 0 },
{ "id": 126, "nombre": "Amanda", "activo": 1 },
{ "id": 127, "nombre": "Hedda", "activo": 0 },
{ "id": 128, "nombre": "Neala", "activo": 0 },
{ "id": 129, "nombre": "Dorette", "activo": 0 },
{ "id": 130, "nombre": "Barbabra", "activo": 1 },
{ "id": 131, "nombre": "Jinny", "activo": 0 },
{ "id": 132, "nombre": "Tania", "activo": 1 },
{ "id": 133, "nombre": "Eugenie", "activo": 1 },
{ "id": 134, "nombre": "Toinette", "activo": 0 },
{ "id": 135, "nombre": "Morganica", "activo": 1 },
{ "id": 136, "nombre": "Brietta", "activo": 0 },
{ "id": 137, "nombre": "Conrado", "activo": 1 },
{ "id": 138, "nombre": "Lezlie", "activo": 0 },
{ "id": 139, "nombre": "Eugenie", "activo": 0 },
{ "id": 140, "nombre": "Dulcine", "activo": 0 },
{ "id": 141, "nombre": "Kylen", "activo": 1 },
{ "id": 142, "nombre": "Egon", "activo": 1 },
{ "id": 143, "nombre": "Minta", "activo": 0 },
{ "id": 144, "nombre": "Olenka", "activo": 1 },
{ "id": 145, "nombre": "Carmelina", "activo": 1 },
{ "id": 146, "nombre": "Ignacius", "activo": 1 },
{ "id": 147, "nombre": "Florida", "activo": 1 },
{ "id": 148, "nombre": "Lizbeth", "activo": 0 },
{ "id": 149, "nombre": "Guilbert", "activo": 0 },
{ "id": 150, "nombre": "Fidelity", "activo": 1 },
{ "id": 151, "nombre": "Eda", "activo": 0 },
{ "id": 152, "nombre": "Coletta", "activo": 1 },
{ "id": 153, "nombre": "Petronille", "activo": 0 },
{ "id": 154, "nombre": "Travers", "activo": 0 },
{ "id": 155, "nombre": "Corey", "activo": 0 },
{ "id": 156, "nombre": "Brandise", "activo": 1 },
{ "id": 157, "nombre": "Will", "activo": 0 },
{ "id": 158, "nombre": "Cooper", "activo": 1 },
{ "id": 159, "nombre": "Dannel", "activo": 0 },
{ "id": 160, "nombre": "Anetta", "activo": 0 },
{ "id": 161, "nombre": "Wayland", "activo": 0 },
{ "id": 162, "nombre": "Hatty", "activo": 1 },
{ "id": 163, "nombre": "Miltie", "activo": 1 },
{ "id": 164, "nombre": "Bernetta", "activo": 0 },
{ "id": 165, "nombre": "Leola", "activo": 0 },
{ "id": 166, "nombre": "Zena", "activo": 0 },
{ "id": 167, "nombre": "Galven", "activo": 0 },
{ "id": 168, "nombre": "Gerrilee", "activo": 0 },
{ "id": 169, "nombre": "Marcel", "activo": 0 },
{ "id": 170, "nombre": "Leann", "activo": 0 },
{ "id": 171, "nombre": "Lorrayne", "activo": 0 },
{ "id": 172, "nombre": "Darsey", "activo": 0 },
{ "id": 173, "nombre": "Cristine", "activo": 1 },
{ "id": 174, "nombre": "Jarrod", "activo": 1 },
{ "id": 175, "nombre": "Zerk", "activo": 0 },
{ "id": 176, "nombre": "Benedicto", "activo": 0 },
{ "id": 177, "nombre": "Laurent", "activo": 0 },
{ "id": 178, "nombre": "Patty", "activo": 1 },
{ "id": 179, "nombre": "Cornelius", "activo": 1 },
{ "id": 180, "nombre": "Dulce", "activo": 0 },
{ "id": 181, "nombre": "Aland", "activo": 0 },
{ "id": 182, "nombre": "Leeanne", "activo": 1 },
{ "id": 183, "nombre": "Nadeen", "activo": 0 },
{ "id": 184, "nombre": "Allis", "activo": 0 },
{ "id": 185, "nombre": "Gaylor", "activo": 1 },
{ "id": 186, "nombre": "Garth", "activo": 1 },
{ "id": 187, "nombre": "Amalie", "activo": 1 },
{ "id": 188, "nombre": "Rennie", "activo": 1 },
{ "id": 189, "nombre": "Quinn", "activo": 1 },
{ "id": 190, "nombre": "Shem", "activo": 0 },
{ "id": 191, "nombre": "Solomon", "activo": 0 },
{ "id": 192, "nombre": "Hubey", "activo": 0 },
{ "id": 193, "nombre": "Enrica", "activo": 1 },
{ "id": 194, "nombre": "Diego", "activo": 1 },
{ "id": 195, "nombre": "Artemas", "activo": 1 },
{ "id": 196, "nombre": "Dalenna", "activo": 0 },
{ "id": 197, "nombre": "Theo", "activo": 1 },
{ "id": 198, "nombre": "Vonni", "activo": 1 },
{ "id": 199, "nombre": "Meyer", "activo": 1 },
{ "id": 200, "nombre": "Anne", "activo": 0 },
{ "id": 201, "nombre": "Jorgan", "activo": 0 },
{ "id": 202, "nombre": "Krispin", "activo": 0 },
{ "id": 203, "nombre": "Bradly", "activo": 1 },
{ "id": 204, "nombre": "Neill", "activo": 0 },
{ "id": 205, "nombre": "Marlo", "activo": 1 },
{ "id": 206, "nombre": "Curtis", "activo": 1 },
{ "id": 207, "nombre": "Chrystal", "activo": 1 },
{ "id": 208, "nombre": "Ty", "activo": 1 },
{ "id": 209, "nombre": "Claudelle", "activo": 1 },
{ "id": 210, "nombre": "Leon", "activo": 1 },
{ "id": 211, "nombre": "Angel", "activo": 1 },
{ "id": 212, "nombre": "Farlay", "activo": 1 },
{ "id": 213, "nombre": "Harley", "activo": 1 },
{ "id": 214, "nombre": "Ferdie", "activo": 1 },
{ "id": 215, "nombre": "Bax", "activo": 0 },
{ "id": 216, "nombre": "Felipe", "activo": 1 },
{ "id": 217, "nombre": "Juditha", "activo": 1 },
{ "id": 218, "nombre": "Violante", "activo": 0 },
{ "id": 219, "nombre": "Piper", "activo": 0 },
{ "id": 220, "nombre": "Arabella", "activo": 0 },
{ "id": 221, "nombre": "Aurlie", "activo": 0 },
{ "id": 222, "nombre": "Dione", "activo": 0 },
{ "id": 223, "nombre": "Jaye", "activo": 0 },
{ "id": 224, "nombre": "My", "activo": 0 },
{ "id": 225, "nombre": "Donaugh", "activo": 0 },
{ "id": 226, "nombre": "Sadie", "activo": 1 },
{ "id": 227, "nombre": "Virge", "activo": 0 },
{ "id": 228, "nombre": "Peria", "activo": 0 },
{ "id": 229, "nombre": "Morgen", "activo": 0 },
{ "id": 230, "nombre": "Eberhard", "activo": 1 },
{ "id": 231, "nombre": "Carmelita", "activo": 0 },
{ "id": 232, "nombre": "Lavena", "activo": 0 },
{ "id": 233, "nombre": "Kahaleel", "activo": 0 },
{ "id": 234, "nombre": "Kalli", "activo": 0 },
{ "id": 235, "nombre": "Harrietta", "activo": 1 },
{ "id": 236, "nombre": "Cale", "activo": 0 },
{ "id": 237, "nombre": "Nisse", "activo": 1 },
{ "id": 238, "nombre": "Daisy", "activo": 0 },
{ "id": 239, "nombre": "Dean", "activo": 1 },
{ "id": 240, "nombre": "Inesita", "activo": 0 },
{ "id": 241, "nombre": "Allie", "activo": 0 },
{ "id": 242, "nombre": "Audrye", "activo": 0 },
{ "id": 243, "nombre": "Ricki", "activo": 0 },
{ "id": 244, "nombre": "Fonz", "activo": 0 },
{ "id": 245, "nombre": "Sheffie", "activo": 0 },
{ "id": 246, "nombre": "Silvia", "activo": 0 },
{ "id": 247, "nombre": "Herold", "activo": 0 },
{ "id": 248, "nombre": "Joane", "activo": 0 },
{ "id": 249, "nombre": "Anallese", "activo": 0 },
{ "id": 250, "nombre": "Hort", "activo": 1 },
{ "id": 251, "nombre": "Zelda", "activo": 0 },
{ "id": 252, "nombre": "Tonia", "activo": 1 },
{ "id": 253, "nombre": "Joyann", "activo": 0 },
{ "id": 254, "nombre": "Babbie", "activo": 1 },
{ "id": 255, "nombre": "Jessie", "activo": 0 },
{ "id": 256, "nombre": "Isidore", "activo": 1 },
{ "id": 257, "nombre": "Blinnie", "activo": 0 },
{ "id": 258, "nombre": "Abey", "activo": 1 },
{ "id": 259, "nombre": "Hilario", "activo": 1 },
{ "id": 260, "nombre": "Kylen", "activo": 0 },
{ "id": 261, "nombre": "Falkner", "activo": 1 },
{ "id": 262, "nombre": "Neely", "activo": 1 },
{ "id": 263, "nombre": "Herrick", "activo": 0 },
{ "id": 264, "nombre": "Reggi", "activo": 0 },
{ "id": 265, "nombre": "Natale", "activo": 1 },
{ "id": 266, "nombre": "Fairleigh", "activo": 1 },
{ "id": 267, "nombre": "Meagan", "activo": 0 },
{ "id": 268, "nombre": "Lizzy", "activo": 0 },
{ "id": 269, "nombre": "Basil", "activo": 1 },
{ "id": 270, "nombre": "Nickie", "activo": 0 },
{ "id": 271, "nombre": "Vally", "activo": 1 },
{ "id": 272, "nombre": "Emmerich", "activo": 1 },
{ "id": 273, "nombre": "Silvie", "activo": 0 },
{ "id": 274, "nombre": "Elihu", "activo": 1 },
{ "id": 275, "nombre": "Dulcia", "activo": 1 },
{ "id": 276, "nombre": "Arnuad", "activo": 1 },
{ "id": 277, "nombre": "Gray", "activo": 0 },
{ "id": 278, "nombre": "Lionel", "activo": 0 },
{ "id": 279, "nombre": "Gabriello", "activo": 1 },
{ "id": 280, "nombre": "Craggy", "activo": 0 },
{ "id": 281, "nombre": "Filbert", "activo": 1 },
{ "id": 282, "nombre": "Tiphani", "activo": 0 },
{ "id": 283, "nombre": "Kimberli", "activo": 0 },
{ "id": 284, "nombre": "Garik", "activo": 0 },
{ "id": 285, "nombre": "Bettina", "activo": 0 },
{ "id": 286, "nombre": "Joshua", "activo": 1 },
{ "id": 287, "nombre": "Nerta", "activo": 0 },
{ "id": 288, "nombre": "Marena", "activo": 0 },
{ "id": 289, "nombre": "Joannes", "activo": 1 },
{ "id": 290, "nombre": "Neville", "activo": 1 },
{ "id": 291, "nombre": "Gladi", "activo": 0 },
{ "id": 292, "nombre": "Kaylil", "activo": 1 },
{ "id": 293, "nombre": "Robina", "activo": 0 },
{ "id": 294, "nombre": "Jacquenette", "activo": 0 },
{ "id": 295, "nombre": "Melicent", "activo": 1 },
{ "id": 296, "nombre": "Sandra", "activo": 1 },
{ "id": 297, "nombre": "Isaac", "activo": 1 },
{ "id": 298, "nombre": "Yehudit", "activo": 1 },
{ "id": 299, "nombre": "Cordie", "activo": 0 },
{ "id": 300, "nombre": "Tabbitha", "activo": 0 },
{ "id": 301, "nombre": "Beret", "activo": 1 },
{ "id": 302, "nombre": "Angie", "activo": 1 },
{ "id": 303, "nombre": "Jaquenetta", "activo": 0 },
{ "id": 304, "nombre": "Laurence", "activo": 1 },
{ "id": 305, "nombre": "Dallas", "activo": 1 },
{ "id": 306, "nombre": "Gwenette", "activo": 0 },
{ "id": 307, "nombre": "Ignace", "activo": 0 },
{ "id": 308, "nombre": "Robinet", "activo": 0 },
{ "id": 309, "nombre": "Cathe", "activo": 0 },
{ "id": 310, "nombre": "Cornela", "activo": 0 },
{ "id": 311, "nombre": "Luis", "activo": 0 },
{ "id": 312, "nombre": "Elset", "activo": 1 },
{ "id": 313, "nombre": "Brandea", "activo": 0 },
{ "id": 314, "nombre": "Hilliary", "activo": 0 },
{ "id": 315, "nombre": "Kaia", "activo": 1 },
{ "id": 316, "nombre": "Goldina", "activo": 0 },
{ "id": 317, "nombre": "Barrett", "activo": 0 },
{ "id": 318, "nombre": "Ashlen", "activo": 1 },
{ "id": 319, "nombre": "Arnie", "activo": 1 },
{ "id": 320, "nombre": "Celestia", "activo": 0 },
{ "id": 321, "nombre": "Gretchen", "activo": 1 },
{ "id": 322, "nombre": "Karyl", "activo": 0 },
{ "id": 323, "nombre": "Stormi", "activo": 0 },
{ "id": 324, "nombre": "Raff", "activo": 1 },
{ "id": 325, "nombre": "Dorthy", "activo": 0 },
{ "id": 326, "nombre": "Hart", "activo": 0 },
{ "id": 327, "nombre": "Beverley", "activo": 0 },
{ "id": 328, "nombre": "Angel", "activo": 1 },
{ "id": 329, "nombre": "Rudiger", "activo": 1 },
{ "id": 330, "nombre": "Eachelle", "activo": 0 },
{ "id": 331, "nombre": "Leonhard", "activo": 0 },
{ "id": 332, "nombre": "Erinn", "activo": 0 },
{ "id": 333, "nombre": "Buddy", "activo": 0 },
{ "id": 334, "nombre": "Jessi", "activo": 1 },
{ "id": 335, "nombre": "Loleta", "activo": 0 },
{ "id": 336, "nombre": "Nikaniki", "activo": 1 },
{ "id": 337, "nombre": "Demetris", "activo": 0 },
{ "id": 338, "nombre": "Hamilton", "activo": 1 },
{ "id": 339, "nombre": "Lilyan", "activo": 0 },
{ "id": 340, "nombre": "Wes", "activo": 1 },
{ "id": 341, "nombre": "Murvyn", "activo": 1 },
{ "id": 342, "nombre": "Indira", "activo": 0 },
{ "id": 343, "nombre": "Rosaleen", "activo": 0 },
{ "id": 344, "nombre": "Serena", "activo": 0 },
{ "id": 345, "nombre": "Rosamund", "activo": 1 },
{ "id": 346, "nombre": "Karlotta", "activo": 0 },
{ "id": 347, "nombre": "Fransisco", "activo": 1 },
{ "id": 348, "nombre": "Kyle", "activo": 1 },
{ "id": 349, "nombre": "Farley", "activo": 0 },
{ "id": 350, "nombre": "Wendeline", "activo": 0 },
{ "id": 351, "nombre": "Enoch", "activo": 0 },
{ "id": 352, "nombre": "Lotti", "activo": 1 },
{ "id": 353, "nombre": "Walton", "activo": 0 },
{ "id": 354, "nombre": "Moyra", "activo": 0 },
{ "id": 355, "nombre": "Thayne", "activo": 1 },
{ "id": 356, "nombre": "Petr", "activo": 0 },
{ "id": 357, "nombre": "Beatrix", "activo": 1 },
{ "id": 358, "nombre": "Codi", "activo": 0 },
{ "id": 359, "nombre": "Kordula", "activo": 0 },
{ "id": 360, "nombre": "Sari", "activo": 0 },
{ "id": 361, "nombre": "Katerina", "activo": 0 },
{ "id": 362, "nombre": "Caron", "activo": 1 },
{ "id": 363, "nombre": "Lambert", "activo": 0 },
{ "id": 364, "nombre": "Elvera", "activo": 1 },
{ "id": 365, "nombre": "Dionysus", "activo": 1 },
{ "id": 366, "nombre": "Reta", "activo": 1 },
{ "id": 367, "nombre": "Staffard", "activo": 0 },
{ "id": 368, "nombre": "Guido", "activo": 1 },
{ "id": 369, "nombre": "Chevalier", "activo": 1 },
{ "id": 370, "nombre": "Emilia", "activo": 1 },
{ "id": 371, "nombre": "Etta", "activo": 1 },
{ "id": 372, "nombre": "Sybil", "activo": 1 },
{ "id": 373, "nombre": "Abbey", "activo": 1 },
{ "id": 374, "nombre": "Kordula", "activo": 1 },
{ "id": 375, "nombre": "Kora", "activo": 0 },
{ "id": 376, "nombre": "Jude", "activo": 1 },
{ "id": 377, "nombre": "Zorine", "activo": 1 },
{ "id": 378, "nombre": "Coreen", "activo": 0 },
{ "id": 379, "nombre": "Lesya", "activo": 0 },
{ "id": 380, "nombre": "Orin", "activo": 0 },
{ "id": 381, "nombre": "Neilla", "activo": 1 },
{ "id": 382, "nombre": "Brinn", "activo": 0 },
{ "id": 383, "nombre": "Agata", "activo": 1 },
{ "id": 384, "nombre": "Chrissy", "activo": 0 },
{ "id": 385, "nombre": "Katusha", "activo": 0 },
{ "id": 386, "nombre": "Cal", "activo": 1 },
{ "id": 387, "nombre": "Obadiah", "activo": 0 },
{ "id": 388, "nombre": "Olivia", "activo": 0 },
{ "id": 389, "nombre": "Joanna", "activo": 1 },
{ "id": 390, "nombre": "Cornela", "activo": 0 },
{ "id": 391, "nombre": "Kass", "activo": 0 },
{ "id": 392, "nombre": "Upton", "activo": 0 },
{ "id": 393, "nombre": "Gal", "activo": 1 },
{ "id": 394, "nombre": "Gerri", "activo": 0 },
{ "id": 395, "nombre": "Granville", "activo": 0 },
{ "id": 396, "nombre": "Gretal", "activo": 0 },
{ "id": 397, "nombre": "Fiona", "activo": 1 },
{ "id": 398, "nombre": "Wolfy", "activo": 1 },
{ "id": 399, "nombre": "Aloise", "activo": 1 },
{ "id": 400, "nombre": "Bernelle", "activo": 0 },
{ "id": 401, "nombre": "Natal", "activo": 0 },
{ "id": 402, "nombre": "Jewelle", "activo": 0 },
{ "id": 403, "nombre": "Tabina", "activo": 1 },
{ "id": 404, "nombre": "Tana", "activo": 1 },
{ "id": 405, "nombre": "Patrizio", "activo": 1 },
{ "id": 406, "nombre": "Tiffy", "activo": 1 },
{ "id": 407, "nombre": "Griselda", "activo": 1 },
{ "id": 408, "nombre": "Ceciley", "activo": 1 },
{ "id": 409, "nombre": "Ludvig", "activo": 0 },
{ "id": 410, "nombre": "Daron", "activo": 0 },
{ "id": 411, "nombre": "Warner", "activo": 0 },
{ "id": 412, "nombre": "Brent", "activo": 0 },
{ "id": 413, "nombre": "Lynnett", "activo": 1 },
{ "id": 414, "nombre": "Phaedra", "activo": 0 },
{ "id": 415, "nombre": "Jervis", "activo": 0 },
{ "id": 416, "nombre": "Gerty", "activo": 1 },
{ "id": 417, "nombre": "Brianne", "activo": 1 },
{ "id": 418, "nombre": "Moise", "activo": 1 },
{ "id": 419, "nombre": "Debra", "activo": 1 },
{ "id": 420, "nombre": "Magdalen", "activo": 1 },
{ "id": 421, "nombre": "Tierney", "activo": 0 },
{ "id": 422, "nombre": "Shelby", "activo": 0 },
{ "id": 423, "nombre": "Grove", "activo": 0 },
{ "id": 424, "nombre": "Hurlee", "activo": 1 },
{ "id": 425, "nombre": "Tate", "activo": 0 },
{ "id": 426, "nombre": "Taddeusz", "activo": 1 },
{ "id": 427, "nombre": "Russ", "activo": 1 },
{ "id": 428, "nombre": "Meridel", "activo": 1 },
{ "id": 429, "nombre": "Bellanca", "activo": 0 },
{ "id": 430, "nombre": "Lorelle", "activo": 0 },
{ "id": 431, "nombre": "Mitzi", "activo": 0 },
{ "id": 432, "nombre": "Gordon", "activo": 0 },
{ "id": 433, "nombre": "Gui", "activo": 1 },
{ "id": 434, "nombre": "Barrie", "activo": 0 },
{ "id": 435, "nombre": "Ware", "activo": 0 },
{ "id": 436, "nombre": "Addy", "activo": 0 },
{ "id": 437, "nombre": "Doralynne", "activo": 0 },
{ "id": 438, "nombre": "Rob", "activo": 1 },
{ "id": 439, "nombre": "Leilah", "activo": 1 },
{ "id": 440, "nombre": "Grata", "activo": 1 },
{ "id": 441, "nombre": "Rana", "activo": 1 },
{ "id": 442, "nombre": "Francisco", "activo": 1 },
{ "id": 443, "nombre": "Vasili", "activo": 1 },
{ "id": 444, "nombre": "Vale", "activo": 1 },
{ "id": 445, "nombre": "Davin", "activo": 1 },
{ "id": 446, "nombre": "Lucias", "activo": 0 },
{ "id": 447, "nombre": "Aigneis", "activo": 0 },
{ "id": 448, "nombre": "Whitney", "activo": 1 },
{ "id": 449, "nombre": "Hatty", "activo": 1 },
{ "id": 450, "nombre": "Bride", "activo": 0 },
{ "id": 451, "nombre": "Melly", "activo": 0 },
{ "id": 452, "nombre": "Noella", "activo": 0 },
{ "id": 453, "nombre": "Mariquilla", "activo": 1 },
{ "id": 454, "nombre": "Gerald", "activo": 0 },
{ "id": 455, "nombre": "Ainslee", "activo": 1 },
{ "id": 456, "nombre": "Olympia", "activo": 0 },
{ "id": 457, "nombre": "Rois", "activo": 1 },
{ "id": 458, "nombre": "Alix", "activo": 1 },
{ "id": 459, "nombre": "Hamnet", "activo": 0 },
{ "id": 460, "nombre": "Gretta", "activo": 1 },
{ "id": 461, "nombre": "Robers", "activo": 1 },
{ "id": 462, "nombre": "Sayers", "activo": 0 },
{ "id": 463, "nombre": "Blythe", "activo": 1 },
{ "id": 464, "nombre": "Ganny", "activo": 1 },
{ "id": 465, "nombre": "Wendel", "activo": 1 },
{ "id": 466, "nombre": "Jule", "activo": 0 },
{ "id": 467, "nombre": "Martina", "activo": 1 },
{ "id": 468, "nombre": "Mariette", "activo": 0 },
{ "id": 469, "nombre": "Bancroft", "activo": 0 },
{ "id": 470, "nombre": "Reid", "activo": 0 },
{ "id": 471, "nombre": "Ulrick", "activo": 0 },
{ "id": 472, "nombre": "Toinette", "activo": 0 },
{ "id": 473, "nombre": "Alika", "activo": 0 },
{ "id": 474, "nombre": "Corby", "activo": 0 },
{ "id": 475, "nombre": "Eldridge", "activo": 1 },
{ "id": 476, "nombre": "Esmaria", "activo": 1 },
{ "id": 477, "nombre": "Shepperd", "activo": 1 },
{ "id": 478, "nombre": "Leslie", "activo": 1 },
{ "id": 479, "nombre": "Nathanael", "activo": 1 },
{ "id": 480, "nombre": "Berry", "activo": 1 },
{ "id": 481, "nombre": "Briny", "activo": 0 },
{ "id": 482, "nombre": "Woodrow", "activo": 1 },
{ "id": 483, "nombre": "Tabb", "activo": 1 },
{ "id": 484, "nombre": "Fiann", "activo": 0 },
{ "id": 485, "nombre": "Cass", "activo": 0 },
{ "id": 486, "nombre": "Merry", "activo": 0 },
{ "id": 487, "nombre": "Florie", "activo": 0 },
{ "id": 488, "nombre": "Ainsley", "activo": 1 },
{ "id": 489, "nombre": "Edsel", "activo": 1 },
{ "id": 490, "nombre": "Ransom", "activo": 0 },
{ "id": 491, "nombre": "Mimi", "activo": 0 },
{ "id": 492, "nombre": "Salim", "activo": 1 },
{ "id": 493, "nombre": "Austen", "activo": 1 },
{ "id": 494, "nombre": "Gail", "activo": 0 },
{ "id": 495, "nombre": "Greer", "activo": 1 },
{ "id": 496, "nombre": "Adelice", "activo": 0 },
{ "id": 497, "nombre": "Sibyl", "activo": 0 },
{ "id": 498, "nombre": "Thane", "activo": 1 },
{ "id": 499, "nombre": "Yanaton", "activo": 0 },
{ "id": 500, "nombre": "Em", "activo": 1 },
{ "id": 501, "nombre": "Dannie", "activo": 1 },
{ "id": 502, "nombre": "Ernesta", "activo": 1 },
{ "id": 503, "nombre": "Sashenka", "activo": 1 },
{ "id": 504, "nombre": "Isac", "activo": 0 },
{ "id": 505, "nombre": "Willabella", "activo": 1 },
{ "id": 506, "nombre": "Cristy", "activo": 0 },
{ "id": 507, "nombre": "Craig", "activo": 0 },
{ "id": 508, "nombre": "Prescott", "activo": 1 },
{ "id": 509, "nombre": "Svend", "activo": 0 },
{ "id": 510, "nombre": "Kaylee", "activo": 0 },
{ "id": 511, "nombre": "Orrin", "activo": 1 },
{ "id": 512, "nombre": "Thia", "activo": 0 },
{ "id": 513, "nombre": "Bradford", "activo": 1 },
{ "id": 514, "nombre": "Giordano", "activo": 1 },
{ "id": 515, "nombre": "Sarette", "activo": 1 },
{ "id": 516, "nombre": "Sarina", "activo": 1 },
{ "id": 517, "nombre": "Asher", "activo": 0 },
{ "id": 518, "nombre": "Greg", "activo": 0 },
{ "id": 519, "nombre": "Nathan", "activo": 0 },
{ "id": 520, "nombre": "Charlton", "activo": 0 },
{ "id": 521, "nombre": "Codi", "activo": 1 },
{ "id": 522, "nombre": "Dallas", "activo": 0 },
{ "id": 523, "nombre": "Kylie", "activo": 0 },
{ "id": 524, "nombre": "Benn", "activo": 0 },
{ "id": 525, "nombre": "Diandra", "activo": 0 },
{ "id": 526, "nombre": "Garth", "activo": 1 },
{ "id": 527, "nombre": "Larina", "activo": 1 },
{ "id": 528, "nombre": "Ara", "activo": 1 },
{ "id": 529, "nombre": "Arielle", "activo": 1 },
{ "id": 530, "nombre": "Silvana", "activo": 1 },
{ "id": 531, "nombre": "Christoffer", "activo": 0 },
{ "id": 532, "nombre": "Wylma", "activo": 0 },
{ "id": 533, "nombre": "Madelaine", "activo": 1 },
{ "id": 534, "nombre": "Otho", "activo": 1 },
{ "id": 535, "nombre": "Lucas", "activo": 0 },
{ "id": 536, "nombre": "Sybilla", "activo": 1 },
{ "id": 537, "nombre": "Dall", "activo": 0 },
{ "id": 538, "nombre": "Reilly", "activo": 1 },
{ "id": 539, "nombre": "Tadio", "activo": 0 },
{ "id": 540, "nombre": "Malchy", "activo": 0 },
{ "id": 541, "nombre": "Ives", "activo": 0 },
{ "id": 542, "nombre": "Jock", "activo": 1 },
{ "id": 543, "nombre": "Nessa", "activo": 1 },
{ "id": 544, "nombre": "Tamiko", "activo": 0 },
{ "id": 545, "nombre": "Robbie", "activo": 0 },
{ "id": 546, "nombre": "Gabrila", "activo": 1 },
{ "id": 547, "nombre": "Bertie", "activo": 0 },
{ "id": 548, "nombre": "Nolly", "activo": 0 },
{ "id": 549, "nombre": "Desirae", "activo": 1 },
{ "id": 550, "nombre": "Sandro", "activo": 1 },
{ "id": 551, "nombre": "Obie", "activo": 0 },
{ "id": 552, "nombre": "Emyle", "activo": 1 },
{ "id": 553, "nombre": "Regen", "activo": 0 },
{ "id": 554, "nombre": "Lisabeth", "activo": 1 },
{ "id": 555, "nombre": "Phylis", "activo": 0 },
{ "id": 556, "nombre": "Benita", "activo": 0 },
{ "id": 557, "nombre": "Karoly", "activo": 0 },
{ "id": 558, "nombre": "Camellia", "activo": 1 },
{ "id": 559, "nombre": "Marnie", "activo": 1 },
{ "id": 560, "nombre": "Dyanne", "activo": 1 },
{ "id": 561, "nombre": "Jean", "activo": 1 },
{ "id": 562, "nombre": "Horatia", "activo": 0 },
{ "id": 563, "nombre": "Tabbatha", "activo": 0 },
{ "id": 564, "nombre": "Gorden", "activo": 0 },
{ "id": 565, "nombre": "Christin", "activo": 0 },
{ "id": 566, "nombre": "Finley", "activo": 1 },
{ "id": 567, "nombre": "Greer", "activo": 1 },
{ "id": 568, "nombre": "Pall", "activo": 1 },
{ "id": 569, "nombre": "Fran", "activo": 1 },
{ "id": 570, "nombre": "Nester", "activo": 0 },
{ "id": 571, "nombre": "Malinde", "activo": 0 },
{ "id": 572, "nombre": "Eva", "activo": 0 },
{ "id": 573, "nombre": "La verne", "activo": 0 },
{ "id": 574, "nombre": "Livvy", "activo": 1 },
{ "id": 575, "nombre": "Rriocard", "activo": 0 },
{ "id": 576, "nombre": "Wilbert", "activo": 0 },
{ "id": 577, "nombre": "Dag", "activo": 0 },
{ "id": 578, "nombre": "Jarrod", "activo": 1 },
{ "id": 579, "nombre": "Dacy", "activo": 1 },
{ "id": 580, "nombre": "Louisa", "activo": 1 },
{ "id": 581, "nombre": "Bary", "activo": 0 },
{ "id": 582, "nombre": "Yvette", "activo": 1 },
{ "id": 583, "nombre": "Margot", "activo": 1 },
{ "id": 584, "nombre": "Buckie", "activo": 0 },
{ "id": 585, "nombre": "Lin", "activo": 1 },
{ "id": 586, "nombre": "Nickie", "activo": 0 },
{ "id": 587, "nombre": "Ingunna", "activo": 1 },
{ "id": 588, "nombre": "Cordy", "activo": 1 },
{ "id": 589, "nombre": "Mehetabel", "activo": 1 },
{ "id": 590, "nombre": "Osmund", "activo": 1 },
{ "id": 591, "nombre": "Pen", "activo": 1 },
{ "id": 592, "nombre": "Kirk", "activo": 1 },
{ "id": 593, "nombre": "Malinda", "activo": 1 },
{ "id": 594, "nombre": "Aldric", "activo": 1 },
{ "id": 595, "nombre": "Milena", "activo": 0 },
{ "id": 596, "nombre": "Tedda", "activo": 0 },
{ "id": 597, "nombre": "Orren", "activo": 1 },
{ "id": 598, "nombre": "Yalonda", "activo": 1 },
{ "id": 599, "nombre": "Heddi", "activo": 1 },
{ "id": 600, "nombre": "Phillipp", "activo": 1 },
{ "id": 601, "nombre": "Eberto", "activo": 0 },
{ "id": 602, "nombre": "Vernon", "activo": 1 },
{ "id": 603, "nombre": "Cathie", "activo": 0 },
{ "id": 604, "nombre": "Ilsa", "activo": 0 },
{ "id": 605, "nombre": "Loraine", "activo": 0 },
{ "id": 606, "nombre": "Gretal", "activo": 0 },
{ "id": 607, "nombre": "Carmen", "activo": 1 },
{ "id": 608, "nombre": "Hort", "activo": 1 },
{ "id": 609, "nombre": "Emlyn", "activo": 0 },
{ "id": 610, "nombre": "Kimmi", "activo": 0 },
{ "id": 611, "nombre": "Darcee", "activo": 1 },
{ "id": 612, "nombre": "Zarah", "activo": 0 },
{ "id": 613, "nombre": "Caterina", "activo": 0 },
{ "id": 614, "nombre": "Kendell", "activo": 1 },
{ "id": 615, "nombre": "Bari", "activo": 1 },
{ "id": 616, "nombre": "Isaak", "activo": 1 },
{ "id": 617, "nombre": "Allie", "activo": 1 },
{ "id": 618, "nombre": "Cosmo", "activo": 0 },
{ "id": 619, "nombre": "Nollie", "activo": 1 },
{ "id": 620, "nombre": "Trace", "activo": 1 },
{ "id": 621, "nombre": "Kikelia", "activo": 0 },
{ "id": 622, "nombre": "Latashia", "activo": 0 },
{ "id": 623, "nombre": "Garry", "activo": 1 },
{ "id": 624, "nombre": "Tull", "activo": 1 },
{ "id": 625, "nombre": "Hedy", "activo": 0 },
{ "id": 626, "nombre": "Tarrance", "activo": 0 },
{ "id": 627, "nombre": "Alley", "activo": 1 },
{ "id": 628, "nombre": "Yvette", "activo": 1 },
{ "id": 629, "nombre": "Lucio", "activo": 0 },
{ "id": 630, "nombre": "Dari", "activo": 0 },
{ "id": 631, "nombre": "Neddie", "activo": 0 },
{ "id": 632, "nombre": "Tristan", "activo": 1 },
{ "id": 633, "nombre": "Guillermo", "activo": 1 },
{ "id": 634, "nombre": "Karia", "activo": 0 },
{ "id": 635, "nombre": "Elwood", "activo": 1 },
{ "id": 636, "nombre": "Findlay", "activo": 0 },
{ "id": 637, "nombre": "Martie", "activo": 1 },
{ "id": 638, "nombre": "Angelico", "activo": 0 },
{ "id": 639, "nombre": "Ferguson", "activo": 1 },
{ "id": 640, "nombre": "Morly", "activo": 1 },
{ "id": 641, "nombre": "Opal", "activo": 1 },
{ "id": 642, "nombre": "Jed", "activo": 0 },
{ "id": 643, "nombre": "Colman", "activo": 0 },
{ "id": 644, "nombre": "Nerita", "activo": 1 },
{ "id": 645, "nombre": "Ephrayim", "activo": 1 },
{ "id": 646, "nombre": "Baxy", "activo": 1 },
{ "id": 647, "nombre": "Melicent", "activo": 0 },
{ "id": 648, "nombre": "Devonna", "activo": 0 },
{ "id": 649, "nombre": "Elia", "activo": 1 },
{ "id": 650, "nombre": "Marigold", "activo": 0 },
{ "id": 651, "nombre": "Gisele", "activo": 0 },
{ "id": 652, "nombre": "Arel", "activo": 0 },
{ "id": 653, "nombre": "Dorie", "activo": 0 },
{ "id": 654, "nombre": "Dalston", "activo": 0 },
{ "id": 655, "nombre": "Phillie", "activo": 0 },
{ "id": 656, "nombre": "Cross", "activo": 1 },
{ "id": 657, "nombre": "Ranice", "activo": 0 },
{ "id": 658, "nombre": "Rosaline", "activo": 0 },
{ "id": 659, "nombre": "Joya", "activo": 1 },
{ "id": 660, "nombre": "Ginnie", "activo": 1 },
{ "id": 661, "nombre": "Cyrus", "activo": 1 },
{ "id": 662, "nombre": "Ryun", "activo": 0 },
{ "id": 663, "nombre": "Euell", "activo": 1 },
{ "id": 664, "nombre": "Inglebert", "activo": 0 },
{ "id": 665, "nombre": "Carmelita", "activo": 1 },
{ "id": 666, "nombre": "Julita", "activo": 0 },
{ "id": 667, "nombre": "Eolanda", "activo": 0 },
{ "id": 668, "nombre": "Gerrard", "activo": 0 },
{ "id": 669, "nombre": "Marcello", "activo": 1 },
{ "id": 670, "nombre": "Arvin", "activo": 1 },
{ "id": 671, "nombre": "Nance", "activo": 0 },
{ "id": 672, "nombre": "Lisetta", "activo": 0 },
{ "id": 673, "nombre": "Baxie", "activo": 0 },
{ "id": 674, "nombre": "Shayne", "activo": 0 },
{ "id": 675, "nombre": "Fran", "activo": 1 },
{ "id": 676, "nombre": "Danie", "activo": 0 },
{ "id": 677, "nombre": "Dwight", "activo": 1 },
{ "id": 678, "nombre": "Thorvald", "activo": 1 },
{ "id": 679, "nombre": "Shelia", "activo": 0 },
{ "id": 680, "nombre": "Ranice", "activo": 1 },
{ "id": 681, "nombre": "Viviene", "activo": 0 },
{ "id": 682, "nombre": "Tessy", "activo": 0 },
{ "id": 683, "nombre": "Jo", "activo": 0 },
{ "id": 684, "nombre": "Booth", "activo": 0 },
{ "id": 685, "nombre": "Mag", "activo": 0 },
{ "id": 686, "nombre": "Herve", "activo": 1 },
{ "id": 687, "nombre": "Justis", "activo": 0 },
{ "id": 688, "nombre": "Aldin", "activo": 0 },
{ "id": 689, "nombre": "Falito", "activo": 1 },
{ "id": 690, "nombre": "Web", "activo": 1 },
{ "id": 691, "nombre": "Guenevere", "activo": 0 },
{ "id": 692, "nombre": "Tamiko", "activo": 0 },
{ "id": 693, "nombre": "Ferdie", "activo": 0 },
{ "id": 694, "nombre": "Bevin", "activo": 0 },
{ "id": 695, "nombre": "Whitman", "activo": 1 },
{ "id": 696, "nombre": "Ferguson", "activo": 0 },
{ "id": 697, "nombre": "Eachelle", "activo": 0 },
{ "id": 698, "nombre": "Michaeline", "activo": 1 },
{ "id": 699, "nombre": "Mirelle", "activo": 0 },
{ "id": 700, "nombre": "Gaye", "activo": 0 },
{ "id": 701, "nombre": "Barnebas", "activo": 1 },
{ "id": 702, "nombre": "Martyn", "activo": 0 },
{ "id": 703, "nombre": "Coralie", "activo": 1 },
{ "id": 704, "nombre": "Jannelle", "activo": 0 },
{ "id": 705, "nombre": "Corbin", "activo": 1 },
{ "id": 706, "nombre": "Milton", "activo": 1 },
{ "id": 707, "nombre": "Evangelia", "activo": 1 },
{ "id": 708, "nombre": "Prent", "activo": 0 },
{ "id": 709, "nombre": "Orella", "activo": 1 },
{ "id": 710, "nombre": "Magdalena", "activo": 0 },
{ "id": 711, "nombre": "Tova", "activo": 0 },
{ "id": 712, "nombre": "Wittie", "activo": 1 },
{ "id": 713, "nombre": "Sada", "activo": 1 },
{ "id": 714, "nombre": "Ronalda", "activo": 0 },
{ "id": 715, "nombre": "Maddy", "activo": 1 },
{ "id": 716, "nombre": "Cherlyn", "activo": 0 },
{ "id": 717, "nombre": "Tedda", "activo": 0 },
{ "id": 718, "nombre": "Tanney", "activo": 0 },
{ "id": 719, "nombre": "Joelie", "activo": 0 },
{ "id": 720, "nombre": "Joanne", "activo": 1 },
{ "id": 721, "nombre": "Kelley", "activo": 0 },
{ "id": 722, "nombre": "Brit", "activo": 1 },
{ "id": 723, "nombre": "Quill", "activo": 1 },
{ "id": 724, "nombre": "Giacinta", "activo": 0 },
{ "id": 725, "nombre": "Susette", "activo": 0 },
{ "id": 726, "nombre": "Bette-ann", "activo": 0 },
{ "id": 727, "nombre": "Ilse", "activo": 1 },
{ "id": 728, "nombre": "Torey", "activo": 1 },
{ "id": 729, "nombre": "Helaine", "activo": 1 },
{ "id": 730, "nombre": "Ivan", "activo": 1 },
{ "id": 731, "nombre": "Antin", "activo": 0 },
{ "id": 732, "nombre": "Terry", "activo": 1 },
{ "id": 733, "nombre": "Frasier", "activo": 1 },
{ "id": 734, "nombre": "Shelbi", "activo": 0 },
{ "id": 735, "nombre": "Val", "activo": 1 },
{ "id": 736, "nombre": "Sandor", "activo": 1 },
{ "id": 737, "nombre": "Jo ann", "activo": 1 },
{ "id": 738, "nombre": "Harmonia", "activo": 1 },
{ "id": 739, "nombre": "Saree", "activo": 0 },
{ "id": 740, "nombre": "Arlana", "activo": 0 },
{ "id": 741, "nombre": "Arin", "activo": 0 },
{ "id": 742, "nombre": "Daisie", "activo": 1 },
{ "id": 743, "nombre": "Dedra", "activo": 1 },
{ "id": 744, "nombre": "Vikki", "activo": 0 },
{ "id": 745, "nombre": "Matty", "activo": 1 },
{ "id": 746, "nombre": "Cass", "activo": 1 },
{ "id": 747, "nombre": "Sheryl", "activo": 0 },
{ "id": 748, "nombre": "Deonne", "activo": 1 },
{ "id": 749, "nombre": "Ranee", "activo": 1 },
{ "id": 750, "nombre": "Valeria", "activo": 0 },
{ "id": 751, "nombre": "Henrietta", "activo": 0 },
{ "id": 752, "nombre": "Liv", "activo": 1 },
{ "id": 753, "nombre": "Roley", "activo": 1 },
{ "id": 754, "nombre": "Lucienne", "activo": 1 },
{ "id": 755, "nombre": "Jarret", "activo": 0 },
{ "id": 756, "nombre": "Yetty", "activo": 1 },
{ "id": 757, "nombre": "Clarey", "activo": 1 },
{ "id": 758, "nombre": "Rochette", "activo": 0 },
{ "id": 759, "nombre": "Rafi", "activo": 0 },
{ "id": 760, "nombre": "Sigvard", "activo": 0 },
{ "id": 761, "nombre": "Colleen", "activo": 1 },
{ "id": 762, "nombre": "Denice", "activo": 1 },
{ "id": 763, "nombre": "Saleem", "activo": 1 },
{ "id": 764, "nombre": "Nil", "activo": 0 },
{ "id": 765, "nombre": "Prudy", "activo": 1 },
{ "id": 766, "nombre": "Ario", "activo": 0 },
{ "id": 767, "nombre": "Zitella", "activo": 0 },
{ "id": 768, "nombre": "Lee", "activo": 0 },
{ "id": 769, "nombre": "Yale", "activo": 0 },
{ "id": 770, "nombre": "Florri", "activo": 0 },
{ "id": 771, "nombre": "Bartholomeo", "activo": 1 },
{ "id": 772, "nombre": "Neddy", "activo": 0 },
{ "id": 773, "nombre": "Khalil", "activo": 1 },
{ "id": 774, "nombre": "Hanan", "activo": 1 },
{ "id": 775, "nombre": "Rodolph", "activo": 1 },
{ "id": 776, "nombre": "Caitrin", "activo": 0 },
{ "id": 777, "nombre": "Hedwiga", "activo": 0 },
{ "id": 778, "nombre": "Karlens", "activo": 0 },
{ "id": 779, "nombre": "Philbert", "activo": 0 },
{ "id": 780, "nombre": "Kenneth", "activo": 0 },
{ "id": 781, "nombre": "Persis", "activo": 0 },
{ "id": 782, "nombre": "Karolina", "activo": 0 },
{ "id": 783, "nombre": "Gertrude", "activo": 1 },
{ "id": 784, "nombre": "Betteann", "activo": 0 },
{ "id": 785, "nombre": "Martainn", "activo": 0 },
{ "id": 786, "nombre": "Anneliese", "activo": 0 },
{ "id": 787, "nombre": "Roz", "activo": 1 },
{ "id": 788, "nombre": "Nathanil", "activo": 0 },
{ "id": 789, "nombre": "Dominick", "activo": 1 },
{ "id": 790, "nombre": "Creigh", "activo": 0 },
{ "id": 791, "nombre": "Kayley", "activo": 0 },
{ "id": 792, "nombre": "Maddie", "activo": 0 },
{ "id": 793, "nombre": "Wood", "activo": 1 },
{ "id": 794, "nombre": "Madge", "activo": 1 },
{ "id": 795, "nombre": "Eugenie", "activo": 0 },
{ "id": 796, "nombre": "Rip", "activo": 0 },
{ "id": 797, "nombre": "Yard", "activo": 0 },
{ "id": 798, "nombre": "Milicent", "activo": 0 },
{ "id": 799, "nombre": "Amity", "activo": 0 },
{ "id": 800, "nombre": "Janenna", "activo": 1 },
{ "id": 801, "nombre": "Arin", "activo": 0 },
{ "id": 802, "nombre": "Frank", "activo": 1 },
{ "id": 803, "nombre": "Jefferey", "activo": 1 },
{ "id": 804, "nombre": "Annmaria", "activo": 1 },
{ "id": 805, "nombre": "Albert", "activo": 1 },
{ "id": 806, "nombre": "Grayce", "activo": 0 },
{ "id": 807, "nombre": "Stoddard", "activo": 0 },
{ "id": 808, "nombre": "Jamesy", "activo": 0 },
{ "id": 809, "nombre": "Fremont", "activo": 1 },
{ "id": 810, "nombre": "Nicki", "activo": 1 },
{ "id": 811, "nombre": "Marjory", "activo": 0 },
{ "id": 812, "nombre": "Lydie", "activo": 1 },
{ "id": 813, "nombre": "Talbot", "activo": 0 },
{ "id": 814, "nombre": "Bil", "activo": 0 },
{ "id": 815, "nombre": "Aveline", "activo": 0 },
{ "id": 816, "nombre": "Rosalyn", "activo": 0 },
{ "id": 817, "nombre": "Evelin", "activo": 1 },
{ "id": 818, "nombre": "Leland", "activo": 0 },
{ "id": 819, "nombre": "Townsend", "activo": 1 },
{ "id": 820, "nombre": "Joan", "activo": 0 },
{ "id": 821, "nombre": "Moses", "activo": 1 },
{ "id": 822, "nombre": "Uta", "activo": 1 },
{ "id": 823, "nombre": "Edith", "activo": 0 },
{ "id": 824, "nombre": "Reamonn", "activo": 1 },
{ "id": 825, "nombre": "Haily", "activo": 1 },
{ "id": 826, "nombre": "Benito", "activo": 0 },
{ "id": 827, "nombre": "Bernita", "activo": 0 },
{ "id": 828, "nombre": "Panchito", "activo": 1 },
{ "id": 829, "nombre": "Min", "activo": 0 },
{ "id": 830, "nombre": "Laina", "activo": 0 },
{ "id": 831, "nombre": "Alla", "activo": 0 },
{ "id": 832, "nombre": "Tadeas", "activo": 0 },
{ "id": 833, "nombre": "Nolana", "activo": 0 },
{ "id": 834, "nombre": "Clemmie", "activo": 0 },
{ "id": 835, "nombre": "Orren", "activo": 1 },
{ "id": 836, "nombre": "Tessie", "activo": 1 },
{ "id": 837, "nombre": "Janey", "activo": 0 },
{ "id": 838, "nombre": "Cicely", "activo": 1 },
{ "id": 839, "nombre": "Rollo", "activo": 1 },
{ "id": 840, "nombre": "Duff", "activo": 1 },
{ "id": 841, "nombre": "Nanette", "activo": 0 },
{ "id": 842, "nombre": "Lammond", "activo": 1 },
{ "id": 843, "nombre": "Dael", "activo": 1 },
{ "id": 844, "nombre": "Gunner", "activo": 1 },
{ "id": 845, "nombre": "Rhonda", "activo": 1 },
{ "id": 846, "nombre": "Riobard", "activo": 1 },
{ "id": 847, "nombre": "Joete", "activo": 0 },
{ "id": 848, "nombre": "Sheba", "activo": 0 },
{ "id": 849, "nombre": "Shelton", "activo": 0 },
{ "id": 850, "nombre": "Frances", "activo": 1 },
{ "id": 851, "nombre": "Erhard", "activo": 1 },
{ "id": 852, "nombre": "Perle", "activo": 0 },
{ "id": 853, "nombre": "Paton", "activo": 1 },
{ "id": 854, "nombre": "Martynne", "activo": 1 },
{ "id": 855, "nombre": "Craggy", "activo": 0 },
{ "id": 856, "nombre": "Ardine", "activo": 0 },
{ "id": 857, "nombre": "Riccardo", "activo": 1 },
{ "id": 858, "nombre": "Sigismondo", "activo": 1 },
{ "id": 859, "nombre": "Tabbie", "activo": 0 },
{ "id": 860, "nombre": "Kandy", "activo": 1 },
{ "id": 861, "nombre": "Basilius", "activo": 1 },
{ "id": 862, "nombre": "Ortensia", "activo": 0 },
{ "id": 863, "nombre": "Kristo", "activo": 1 },
{ "id": 864, "nombre": "Tedra", "activo": 0 },
{ "id": 865, "nombre": "Salomone", "activo": 0 },
{ "id": 866, "nombre": "Adria", "activo": 0 },
{ "id": 867, "nombre": "Jasmin", "activo": 0 },
{ "id": 868, "nombre": "Mitzi", "activo": 0 },
{ "id": 869, "nombre": "Manya", "activo": 1 },
{ "id": 870, "nombre": "Nicole", "activo": 0 },
{ "id": 871, "nombre": "Ginger", "activo": 0 },
{ "id": 872, "nombre": "Quintana", "activo": 1 },
{ "id": 873, "nombre": "Flori", "activo": 0 },
{ "id": 874, "nombre": "Janka", "activo": 0 },
{ "id": 875, "nombre": "Aubert", "activo": 0 },
{ "id": 876, "nombre": "Cecilla", "activo": 1 },
{ "id": 877, "nombre": "Bunny", "activo": 0 },
{ "id": 878, "nombre": "Danyette", "activo": 0 },
{ "id": 879, "nombre": "Leopold", "activo": 0 },
{ "id": 880, "nombre": "Emogene", "activo": 1 },
{ "id": 881, "nombre": "Torie", "activo": 0 },
{ "id": 882, "nombre": "Ruthe", "activo": 0 },
{ "id": 883, "nombre": "Welch", "activo": 0 },
{ "id": 884, "nombre": "Winona", "activo": 0 },
{ "id": 885, "nombre": "Dore", "activo": 1 },
{ "id": 886, "nombre": "Shaylynn", "activo": 1 },
{ "id": 887, "nombre": "Lynsey", "activo": 1 },
{ "id": 888, "nombre": "Britt", "activo": 1 },
{ "id": 889, "nombre": "Korey", "activo": 1 },
{ "id": 890, "nombre": "Ancell", "activo": 0 },
{ "id": 891, "nombre": "Matty", "activo": 0 },
{ "id": 892, "nombre": "Diena", "activo": 0 },
{ "id": 893, "nombre": "Skelly", "activo": 1 },
{ "id": 894, "nombre": "Raddy", "activo": 0 },
{ "id": 895, "nombre": "Isobel", "activo": 1 },
{ "id": 896, "nombre": "Mervin", "activo": 1 },
{ "id": 897, "nombre": "Petey", "activo": 1 },
{ "id": 898, "nombre": "Frederique", "activo": 0 },
{ "id": 899, "nombre": "Livy", "activo": 1 },
{ "id": 900, "nombre": "Tallie", "activo": 1 },
{ "id": 901, "nombre": "Heddi", "activo": 1 },
{ "id": 902, "nombre": "Marcelia", "activo": 1 },
{ "id": 903, "nombre": "Teodorico", "activo": 1 },
{ "id": 904, "nombre": "Jamima", "activo": 0 },
{ "id": 905, "nombre": "Fidelia", "activo": 1 },
{ "id": 906, "nombre": "Dud", "activo": 0 },
{ "id": 907, "nombre": "Gasparo", "activo": 1 },
{ "id": 908, "nombre": "Lelia", "activo": 1 },
{ "id": 909, "nombre": "Abeu", "activo": 0 },
{ "id": 910, "nombre": "Regine", "activo": 0 },
{ "id": 911, "nombre": "Lu", "activo": 1 },
{ "id": 912, "nombre": "Al", "activo": 0 },
{ "id": 913, "nombre": "Nealon", "activo": 0 },
{ "id": 914, "nombre": "Willie", "activo": 1 },
{ "id": 915, "nombre": "Lesley", "activo": 0 },
{ "id": 916, "nombre": "Robinetta", "activo": 1 },
{ "id": 917, "nombre": "Ethelin", "activo": 1 },
{ "id": 918, "nombre": "Harriott", "activo": 1 },
{ "id": 919, "nombre": "Mace", "activo": 1 },
{ "id": 920, "nombre": "Clerkclaude", "activo": 0 },
{ "id": 921, "nombre": "Cindee", "activo": 1 },
{ "id": 922, "nombre": "Nettie", "activo": 0 },
{ "id": 923, "nombre": "Torre", "activo": 1 },
{ "id": 924, "nombre": "Gareth", "activo": 1 },
{ "id": 925, "nombre": "Yanaton", "activo": 0 },
{ "id": 926, "nombre": "Morena", "activo": 0 },
{ "id": 927, "nombre": "Suzann", "activo": 1 },
{ "id": 928, "nombre": "Gard", "activo": 0 },
{ "id": 929, "nombre": "Tedra", "activo": 0 },
{ "id": 930, "nombre": "Lacie", "activo": 0 },
{ "id": 931, "nombre": "Osmond", "activo": 0 },
{ "id": 932, "nombre": "Agosto", "activo": 1 },
{ "id": 933, "nombre": "Ian", "activo": 0 },
{ "id": 934, "nombre": "Daryn", "activo": 0 },
{ "id": 935, "nombre": "Dode", "activo": 0 },
{ "id": 936, "nombre": "Saudra", "activo": 0 },
{ "id": 937, "nombre": "Ailey", "activo": 0 },
{ "id": 938, "nombre": "Niki", "activo": 1 },
{ "id": 939, "nombre": "Eula", "activo": 0 },
{ "id": 940, "nombre": "Odelia", "activo": 0 },
{ "id": 941, "nombre": "Aggie", "activo": 0 },
{ "id": 942, "nombre": "Heddi", "activo": 0 },
{ "id": 943, "nombre": "Ranee", "activo": 1 },
{ "id": 944, "nombre": "Rowena", "activo": 0 },
{ "id": 945, "nombre": "Lark", "activo": 0 },
{ "id": 946, "nombre": "Carole", "activo": 0 },
{ "id": 947, "nombre": "Sullivan", "activo": 1 },
{ "id": 948, "nombre": "Arni", "activo": 0 },
{ "id": 949, "nombre": "Clary", "activo": 0 },
{ "id": 950, "nombre": "Teresita", "activo": 0 },
{ "id": 951, "nombre": "Frants", "activo": 1 },
{ "id": 952, "nombre": "Michele", "activo": 0 },
{ "id": 953, "nombre": "Mickie", "activo": 1 },
{ "id": 954, "nombre": "Alwin", "activo": 1 },
{ "id": 955, "nombre": "Brook", "activo": 0 },
{ "id": 956, "nombre": "Alexandra", "activo": 1 },
{ "id": 957, "nombre": "Shantee", "activo": 1 },
{ "id": 958, "nombre": "Yard", "activo": 0 },
{ "id": 959, "nombre": "Tara", "activo": 0 },
{ "id": 960, "nombre": "Dominic", "activo": 0 },
{ "id": 961, "nombre": "Gregoor", "activo": 0 },
{ "id": 962, "nombre": "Reiko", "activo": 1 },
{ "id": 963, "nombre": "Felic", "activo": 1 },
{ "id": 964, "nombre": "Hyacinthe", "activo": 1 },
{ "id": 965, "nombre": "Katti", "activo": 1 },
{ "id": 966, "nombre": "Fred", "activo": 1 },
{ "id": 967, "nombre": "Danyelle", "activo": 0 },
{ "id": 968, "nombre": "Katina", "activo": 1 },
{ "id": 969, "nombre": "Belva", "activo": 1 },
{ "id": 970, "nombre": "Marlene", "activo": 1 },
{ "id": 971, "nombre": "Wolf", "activo": 0 },
{ "id": 972, "nombre": "Mariel", "activo": 0 },
{ "id": 973, "nombre": "Conway", "activo": 1 },
{ "id": 974, "nombre": "Barny", "activo": 1 },
{ "id": 975, "nombre": "Brand", "activo": 0 },
{ "id": 976, "nombre": "Vonni", "activo": 0 },
{ "id": 977, "nombre": "Hersch", "activo": 1 },
{ "id": 978, "nombre": "Ernestus", "activo": 0 },
{ "id": 979, "nombre": "Aguistin", "activo": 0 },
{ "id": 980, "nombre": "Jillian", "activo": 0 },
{ "id": 981, "nombre": "Ajay", "activo": 1 },
{ "id": 982, "nombre": "Traver", "activo": 1 },
{ "id": 983, "nombre": "Micheil", "activo": 1 },
{ "id": 984, "nombre": "Lolita", "activo": 1 },
{ "id": 985, "nombre": "Malissia", "activo": 0 },
{ "id": 986, "nombre": "Shell", "activo": 0 },
{ "id": 987, "nombre": "Halie", "activo": 1 },
{ "id": 988, "nombre": "Dode", "activo": 1 },
{ "id": 989, "nombre": "Iolande", "activo": 1 },
{ "id": 990, "nombre": "Ricoriki", "activo": 1 },
{ "id": 991, "nombre": "Nannette", "activo": 0 },
{ "id": 992, "nombre": "Shepard", "activo": 0 },
{ "id": 993, "nombre": "Margi", "activo": 0 },
{ "id": 994, "nombre": "Katee", "activo": 0 },
{ "id": 995, "nombre": "Kris", "activo": 0 },
{ "id": 996, "nombre": "Sella", "activo": 1 },
{ "id": 997, "nombre": "Taite", "activo": 0 },
{ "id": 998, "nombre": "Hansiain", "activo": 0 },
{ "id": 999, "nombre": "Addie", "activo": 0 },
{ "id": 1000, "nombre": "Locke", "activo": 1 }]

const { Tr, Th, Td, THead, TBody, Sorter } = Table

const Usuario = () => {

    const [data] = useState(data2)

    const onPaginationChange = (page: number) => {
        table.setPageIndex(page - 1)
    }

    const onSelectChange = (value = 0) => {
        table.setPageSize(Number(value))
    }

    const [sorting, setSorting] = useState<ColumnSort[]>([])

    const table = useReactTable({
        data,
        columns,
        state: {
            sorting,
        },
        enableColumnResizing: true,
        columnResizeMode: 'onChange',
        onSortingChange: setSorting,
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
    })

    return (
        <>
            <Table>
                <THead>
                    {table.getHeaderGroups().map((headerGroup) => (
                        <Tr key={headerGroup.id}>
                            {headerGroup.headers.map((header) => {
                                return (
                                    <Th
                                        key={header.id}
                                        colSpan={header.colSpan}
                                        style={{
                                            position: 'relative',
                                            width: header.getSize(),
                                        }}
                                    >
                                        {header.isPlaceholder ? null : (
                                            <div
                                                {...{
                                                    className:
                                                        header.column.getCanSort()
                                                            ? 'cursor-pointer select-none'
                                                            : '',
                                                    onClick:
                                                        header.column.getToggleSortingHandler(),
                                                }}
                                            >
                                                {flexRender(
                                                    header.column.columnDef
                                                        .header,
                                                    header.getContext()
                                                )}
                                                {
                                                    <Sorter
                                                        sort={header.column.getIsSorted()}
                                                    />
                                                }
                                            </div>
                                        )}

                                        {header.column.getCanResize() && (
                                            <div
                                                className={`table-resizer cursor-all-scroll ${header.column.getIsResizing()
                                                        ? 'isResizing'
                                                        : ''
                                                    }`}
                                                onMouseDown={header.getResizeHandler()}
                                                onTouchStart={header.getResizeHandler()}
                                            ></div>
                                        )}

                                    </Th>
                                )
                            })}
                        </Tr>
                    ))}
                </THead>
                <TBody>
                    {table
                        .getRowModel().rows.map((row) => {
                            return (
                                <Tr key={row.id}>
                                    {row.getVisibleCells().map((cell) => {
                                        return (
                                            <Td key={cell.id}>
                                                {flexRender(
                                                    cell.column.columnDef.cell,
                                                    cell.getContext()
                                                )}
                                            </Td>
                                        )
                                    })}
                                </Tr>
                            )
                        })}
                </TBody>
            </Table>
            <div className="flex items-center justify-between mt-4">
                <Pagination
                    pageSize={table.getState().pagination.pageSize}
                    currentPage={table.getState().pagination.pageIndex + 1}
                    total={data.length}
                    onChange={onPaginationChange}
                />
                <div style={{ minWidth: 130 }}>
                    <Select<Option>
                        size="sm"
                        isSearchable={false}
                        value={pageSizeOption.filter(
                            (option) =>
                                option.value ===
                                table.getState().pagination.pageSize
                        )}
                        options={pageSizeOption}
                        onChange={(option) => onSelectChange(option?.value)}
                    />
                </div>
            </div>
        </>
    )
}

export default Usuario